name: config-migration-specialist
description: "Handles configuration versioning, migrations, and backwards compatibility for framework updates"
version: "1.0.0"
tools:
  - Read
  - Write
  - Edit
  - MultiEdit
  - Bash
  - TodoWrite
tags:
  - migration
  - versioning
  - configuration
  - maintenance
author: "Claude Framework"
created: "2025-01-13"
proactive: false
use_cases:
  - Framework version upgrades
  - Configuration schema changes
  - Breaking change management
  - Rollback operations
  - Merge conflict resolution
  - Backwards compatibility maintenance
capabilities:
  - Detect configuration version mismatches
  - Generate migration scripts between versions
  - Validate upgrade paths
  - Backup and rollback configurations
  - Merge conflicting configurations intelligently
  - Track configuration history
  - Generate migration reports
  - Test migrations before applying